config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #  welcome page to the root of my app

  root :to            =>    "welcome#index"


    # users:
  get     "/users"             =>  "users#index",     as: "users"

  # sign up:
  get     "/signup"            =>  "users#new",       as: "new_user"
  post    "/users"             =>  "users#create"

  # show, edit, update, destroy:
  get     "/users/:id"         =>  "users#show",      as: "user"
  get     "/users/:id/edit"    =>  "users#edit",      as: "edit_user"
  put     "/users/:id"         =>  "users#update"
  patch   "/users/:id"         =>  "users#update"
  delete  "/users/:id"         =>  "users#destroy"

  # login
  get     "/login"              =>  "users#login_form"
  post    "/login"              =>  "users#create_login"

  # logout
  get     "/logout"             =>  "users#logout"


    resources :posts
    resources :comments

  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments

end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :comments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController



  def index
    @comments= Comment.all
  end

  def new
    @message = "make your comment"
  end

  def create
    @new_comment = Comment.create(
      content: params[:comment][:content],
      user_id: params[:comment][:user_id],
      post_id: params[:comment][:post_id]
    )

    if @new_comment
      # redirect_to url_for(:controller => :comments, :action => :index)
      redirect_to '/posts/' + @new_comment.post.id.to_s
    else
      redirect_to url_for(:controller => :comments, :action => :new)
    end
  end

    def show
      @comment = Comment.find(params[:id])
      @post_user = @comment.user.fname

      if session[:post_id] # if logged in
        @message = "You're now logged in!"
      else
        @message = "You're not logged in yet"
      end
    end

    def edit
      @comment = Comment.find(params[:id])
    end

    def update
      @comment = Comment.find(params[:id])
      @comment.update({
        content: params[:comment][:content],
        user_id: params[:comment][:user_id],
        post_id: params[:comment][:post_id]
      })

      if (@comment)
        redirect_to url_for(:controller => :comments, :action => :index)
      else
        redirect_to url_for(:controller => :comments, :action => :edit)
      end
    end

    def destroy
      puts "hello" + Comment.find(params[:id]).post.id.to_s
      Comment.delete(params[:id])

      redirect_to url_for(:controller => :comments, :action => :index)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  # where all the methods are defined for the corresponding views

  # displays all posts on index route
  def index
  @posts = Post.all
  end

  def new
  end

  # method is triggered when the router hears a request
  def create
    @new_post = Post.create(
      title: params[:post][:title],
      content: params[:post][:content],
      user_id: params[:post][:user_id]
    )
      # when method create successful redirect user to home page else redirect to sign up
    if @new_post
      redirect_to url_for(:controller => :posts, :action => :index)
      # if not the controller redirects to a new post url
    else
      redirect_to url_for(:controller => :posts, :action => :new)
    end
  end

  def show
    # instance variables are created and can be used in corresponding view
    @post = Post.find(params[:id])
    @post_user = @post.user.fname
    @comments = @post.comments

    if session[:post_id] # if logged in
      @message = "You're now logged in!"
    else
      @message = "You're not logged in yet"
    end
  end

# post can be edited by looking for the id corresponding the post created
  def edit
    @post = Post.find(params[:id])
  end

# THIS METHOD ALLOWS THE TITLE AND CONTENT TO BE UPDATED
  def update
    @post = Post.find(params[:id])
    @post.update({
      title: params[:post][:title],
      content: params[:post][:content],
      user_id: params[:post][:user_id]
    })

    if (@post)
      redirect_to url_for(:controller => :posts, :action => :index)
    else
      redirect_to url_for(:controller => :posts, :action => :edit)
    end
  end

  # THIS METHOD allows to delete the post
  def destroy
    Post.delete(params[:id])
    redirect_to url_for(:controller => :posts, :action => :index)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # where all the methods are defined for the corresponding views
    # users on index route
    def index
      @users  = User.all
    end

    def new
      @message = "sign up to my blog"
    end

    # method is triggered when the router hears a request
    def create
      @new_user = User.create(
      fname: params[:user][:fname],
      lname: params[:user][:lname],
      password: params[:user][:password],
      username: params[:user][:username],
      email: params[:user][:email]
      )
      # when method create successful redirect user to home page else redirect to sign up
      if @new_user
        session[:user_id] = @new_user.id
        redirect_to url_for(:controller => :users, :action => :index)
      else
        redirect_to url_for(:controller => :users, :action => :new)
      end
    end

    def show
        # instance variables are created and can be used in corresponding view

      @user = User.find(params[:id])
      # get users post based on this id
      @user_posts = @user.posts

      if session[:user_id]
        @message = "you are logged in"
      else
        @message = "not logged in yet"
      end
    end

    def edit
      @user = User.find(params[:id])
    end

    def update
    @user = User.find(params[:id])
    @user.update({
      fname: params[:user][:fname],
      lname: params[:user][:lname],
      password: params[:user][:password],
      username: params[:user][:username],
      email: params[:user][:email]
    })

    if (@user)
      redirect_to url_for(:controller => :users, :action => :index)
    else
      redirect_to url_for(:controller => :users, :action => :edit)
    end
  end
  # ends the session and redirect to home
  def destroy
    User.delete(params[:id])
    session.destroy
    redirect_to url_for(:controller => :users, :action => :index)
  end

  def login_form
    if session[:user_id] # if logged in
      @message = "You're logged in!"
    else
      @message = "You're not logged in"
    end
  end

  def create_login
    @user = User.where(username: params[:username], password:
    # finds the first password in array
   params[:password]).first

    if @user
      session[:user_id] = @user.id
      # redirect_to url_for(:controller => :users, :action => :index)
      redirect_to user_path(session[:user_id])
    else
      redirect_to url_for(:controller => :users, :action => :login)
    end
  end

# THIS METHOD allows to end the current session
  def logout
      session.destroy
      redirect_to url_for(:controller => :users, :action => :index)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
# only used for welcome page
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/index.html.erb
<h3>All Comments: </h3>

<%= link_to ("Create new comment"), new_comment_path %>

<br><br>

<% @comments.each do |comment| %>

  <%= comment.content %> <br>

  <br><br>


  <%= link_to 'Delete comment',  { action: :destroy, id: comment.id }, method: :delete %>


<% end %>

app/views/comments/new.html.erb
<%= form_for Comment.new do |f| %>

  <%= f.label :content %>
  <%= f.text_field :content %> <br>

  <%= f.label :user %><br>
  <%= f.collection_select :user_id, User.all, :id, :fname %>


  <%= f.label :post %><br>
  <%= f.collection_select :post_id, Post.all, :id, :title %>

  <br><br>

  <%= f.submit %>
<% end %>

app/views/comments/show.html.erb
<h3>Add comment</h3>

<%= form_for Comment.new do |f| %>

  <%= f.label :content %>
  <%= f.text_field :content %> <br>
  <br>
  <%= f.label :user %><br>
  <%= f.collection_select :user_id, User.all, :id, :fname %>

  <br>
  <%= f.label :post %><br>
  <%= f.collection_select :post_id, Post.all, :id, :title %>

  <br><br>

  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h3>Edit post here</h3>
<!--  This is the form for to edit a post , which will be displayed at "/posts/edit"-->
<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %> <br>

  <%= f.label :content %>
  <%= f.text_field :content %> <br>

  <%= f.label :user %><br>
  <%= f.collection_select :user_id, User.all, :id, :fname %>

  <br><br>

  <%= f.submit %>
<% end %>

app/views/posts/index.htm.erb
<h3>All Posts: </h3>

<%= link_to ("Create new post"), new_post_path %>

<br><br>

<!--this loop will show in the browser a list of all posts  -->
<div class="post_text>"
  <% @posts.each do |post| %>
    <%= post.id %>.
    <%= post.title %> <br>
    <%= post.content %> <br>

  <br><br>

  <%= link_to ("Post show page"), post_path(post.id), {class: "btn btn-primary"} %>
  <br><br>
  <%= link_to 'Delete post', { action: :destroy, id: post.id }, method: :delete %>


  <% end %>
</div>

app/views/posts/new.html.erb
<h3>Create new post!</h3>

<!--this form allows the user to create a new post in the browser  -->
<%= form_for Post.new do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %> <br>

  <%= f.label :content %>
  <%= f.text_field :content %> <br>

  <%= f.label :user %><br>
  <%= f.collection_select :user_id, User.all, :id, :fname %>

  <br><br>

  <%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<h3>Post show page</h3>
<!--displays the post ID, title and content in the browser   -->
<%= @post.id %>.
<%= @post.title %> <br>
<%= @post.content %> <br>
<br>

Blog by: <%= @post.user.fname %> <%= @post.user.lname %>

<br>

<h3>Comments:</h3>
<!--  all the comments are displayed in the browser with this loop-->
<% @comments.each do |comment| %>
<%= comment.content %>|

<% end%>

<h3>Add comment</h3>
<!-- this view will display in the browser a new comment -->
<%= form_for Comment.new do |f| %>

  <%= f.label :content %>
  <%= f.text_field :content %> <br>

  <%= f.label :user %><br>
  <%= f.collection_select :user_id, User.all, :id, :fname %><br>


  <%= f.label :post %><br>
  <%= f.collection_select :post_id, Post.all, :id, :title %><br>

  <br><br>

  <%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<h3>Edit your account:</h3>
<!-- this form will display in the browser a form to edit user details.-->

<%= form_for @user do |f| %>
  <%= f.label :fname %>
  <%= f.text_field :fname %> <br>

  <%= f.label :lname %>
  <%= f.text_field :lname %> <br>

  <%= f.label :username %>
  <%= f.text_field :username %> <br>

  <%= f.label :email %>
  <%= f.text_field :email %> <br>

  <%= f.label :password %>
  <%= f.text_field :password %> <br>

  <%= f.submit %>
<% end %>

app/views/users/index.html.erb
  <!--  @users refers to User.all-->
<% @users.each do |user| %>
  <%= user.id %>.
  <%= user.fname %>,
  <%= user.lname %>,
  <%= user.username %>,
  <%= user.password %>,
  <%= user.email %>

  <br><br>

  <!-- path generates a link to http 3000/users/:id displayed above -->
  <%= link_to ("User show page"), user_path(user.id) %> |
  <%= link_to 'Delete user',  { action: :destroy, id: user.id }, method: :delete %>
  <hr>

<% end %>

app/views/users/login_form.html.erb
<h2>Log in!</h2>

<div><%= @message %></div>

<br><br>

<%= form_tag("/login", method: "post") do %>

  <%= label_tag(:username, "Username:") %>
  <%= text_field_tag(:username) %><br>

  <%= label_tag(:password, "Password:") %>
  <%= text_field_tag(:password) %>

  <%= submit_tag("Submit") %>
<% end %>
Contact GitHub API Training Shop Blog About

app/views/users/logout.html.erb
<h2>See you next time!  Come back soon.</h2>

app/views/users/new.html.erb
<h3>Register for an account here</h3>

  <!--  this is a new form to create a new user-->

<%= form_for User.new do |f| %>
  <%= f.label :fname %><br>
  <%= f.text_field :fname %> <br>

  <%= f.label :lname %><br>
  <%= f.text_field :lname %> <br>

  <%= f.label :username %><br>
  <%= f.text_field :username %> <br>

  <%= f.label :email %><br>
  <%= f.text_field :email %> <br>

  <%= f.label :password %><br>
  <%= f.text_field :password %> <br>
  <br><br>

  <%= f.submit %>

  <% end %>

app/views/users/show.html.erb
<div><%= @message %></div>

<br><br>
<!-- displays each user information from a specific query -->
<%= @user.id %>.
<%= @user.fname %>
<%= @user.lname %>,
<%= @user.username %>,
<%= @user.email %>,
<%= @user.password %>

<hr>

<br><br>

<div>Posts by this user:</div>

<% @user_posts.each do |post| %>
  <%= post.id %>.
  <!-- path generates a link to http 3000/posts/:id displayed above -->
  <%= link_to (post.title), post_path(post.id) %>
  <br><br>
<% end %>
Contact GitHub API Training Shop Blog About
© 2017 GitHub, Inc. Terms Privacy Security Status Help

app/views/welcome/index.html.erb
<!-- displays a welcome message in the root path -->

<div class="welcome" "content" "visible">
  <h2>Ready to give your thoughts!</h2>
</div>